app:
  cert_file_path: "../certs/private_key.pem"
server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
database:
  host: 127.0.0.1
  port: 5432
  user: "user"
  password: "password"
  dbname: "dbname"
  sslmode: "disable"
  pool_connection:
    max_open_conns: 25
    max_idle_conns: 25
    max_life_time: 5
jwt:
  accessTokenDuration:  5  # minutes
  refreshTokenDuration: 30 # days
  issuer: "user_service"
